-- CPAG DATABASE RECOVERY SCRIPT
-- RUN THIS IN YOUR SUPABASE SQL EDITOR ON VPS

-- 1. Create Tables
-- Table: public.users (For authentication and profile)
CREATE TABLE IF NOT EXISTS public.users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    login text NOT NULL UNIQUE,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    password text NOT NULL, -- STORED AS BCRYPT HASH
    role text NOT NULL CHECK (role = ANY (ARRAY['ADMIN'::text, 'USER'::text])),
    preferred_theme text DEFAULT 'system'::text CHECK (preferred_theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])),
    created_at bigint NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()) * 1000)::bigint
);

-- Table: public.accounts (For accounting records)
CREATE TABLE IF NOT EXISTS public.accounts (
    id text PRIMARY KEY,
    data_movimento text NOT NULL,
    local text NOT NULL,
    fornecedor text NOT NULL,
    titulo text NOT NULL,
    empresa text NOT NULL,
    vencimento text NOT NULL,
    valor numeric NOT NULL,
    tipo text NOT NULL,
    categoria text NOT NULL,
    status text NOT NULL,
    observacao text,
    created_at bigint NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()) * 1000)::bigint,
    anexos jsonb DEFAULT '[]'::jsonb
);

-- Table: public.system_settings (For app configuration)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id text PRIMARY KEY,
    account_types jsonb NOT NULL DEFAULT '[]'::jsonb,
    account_categories jsonb NOT NULL DEFAULT '[]'::jsonb,
    account_statuses jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies (Simple for app connection)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all for app') THEN
        CREATE POLICY "Allow all for app" ON public.accounts FOR ALL USING (true) WITH CHECK (true);
        CREATE POLICY "Allow all for app" ON public.users FOR ALL USING (true) WITH CHECK (true);
        CREATE POLICY "Allow all for app" ON public.system_settings FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 4. Insert Default System Settings
INSERT INTO public.system_settings (id, account_types, account_categories, account_statuses) 
VALUES (
    'default', 
    '["DESPESA", "COMPRA"]', 
    '["OUTROS", "ENERGIA", "ALUGUEL", "SALARIOS", "IMPOSTOS", "MERCADORIA", "MARKETING", "MANUTENCAO", "SOFTWARE", "CONBUSTIVEL", "VEICULOS"]', 
    '["PENDENTE", "PAGO", "CANCELADO", "EM ANALISE"]'
) 
ON CONFLICT (id) DO NOTHING;

-- 5. Create a Default Admin User (Password: admin123 - generated by bcrypt)
-- login: admin
-- pass: admin123
INSERT INTO public.users (login, full_name, email, password, role, created_at)
VALUES (
    'admin', 
    'Administrador do Sistema', 
    'admin@cpag.com', 
    '$2a$10$7R9r2jC61uGvGv58uG9K6.K9uG/89tD.tG/89tD.tG/89tD.tG/89tD.', -- Exemplo de hash bcrypt
    'ADMIN',
    (EXTRACT(EPOCH FROM now()) * 1000)::bigint
)
ON CONFLICT (login) DO NOTHING;
