-- Supabase Full Dump
-- Generated by Antigravity

-- Table: public.accounts
CREATE TABLE IF NOT EXISTS public.accounts (
    id text PRIMARY KEY,
    data_movimento text NOT NULL,
    local text NOT NULL,
    fornecedor text NOT NULL,
    titulo text NOT NULL,
    empresa text NOT NULL,
    vencimento text NOT NULL,
    valor numeric NOT NULL,
    tipo text NOT NULL,
    categoria text NOT NULL,
    status text NOT NULL,
    observacao text,
    created_at bigint NOT NULL,
    anexos jsonb DEFAULT '[]'::jsonb
);

-- Table: public.users
CREATE TABLE IF NOT EXISTS public.users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    login text NOT NULL UNIQUE,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    password text NOT NULL,
    role text NOT NULL CHECK (role = ANY (ARRAY['ADMIN'::text, 'USER'::text])),
    preferred_theme text DEFAULT 'system'::text CHECK (preferred_theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])),
    created_at bigint NOT NULL
);

-- Table: public.system_settings
CREATE TABLE IF NOT EXISTS public.system_settings (
    id text PRIMARY KEY,
    account_types jsonb NOT NULL DEFAULT '[]'::jsonb,
    account_categories jsonb NOT NULL DEFAULT '[]'::jsonb,
    account_statuses jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- RLS Policies
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso total para o App" ON public.accounts FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for users" ON public.users FOR ALL USING (true);
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir todo acesso a system_settings" ON public.system_settings FOR ALL USING (true);

INSERT INTO public.system_settings (id, account_types, account_categories, account_statuses, created_at, updated_at) VALUES ('default', '["DESPESA", "COMPRA"]'::jsonb, '["OUTROS", "ENERGIA", "ALUGUEL", "SALARIOS", "IMPOSTOS", "MERCADORIA", "MARKETING", "MANUTENCAO", "SOFTWARE", "CONBUSTIVEL", "VEICULOS"]'::jsonb, '["PENDENTE", "PAGO", "CANCELADO", "EM ANALISE"]'::jsonb, '2026-02-21 02:05:17.505633+00', '2026-02-23 01:44:03.52+00') ON CONFLICT (id) DO NOTHING;

-- Data for accounts
-- Error processing batch 30: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
-- Error processing batch 33: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
-- Error processing batch 36: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
-- Error processing batch 39: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
-- Error processing batch 42: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
-- Error processing batch 45: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
